import com.android.build.gradle.api.AndroidBasePlugin

plugins {
    id 'com.android.application' version '8.5.1' apply false
    id 'com.android.library' version '8.5.1' apply false
}

allprojects {
    group = GROUP
    version = VERSION_NAME

    plugins.withType(JavaBasePlugin).configureEach {
        java {
            toolchain.languageVersion = JavaLanguageVersion.of(17)
        }
    }

    plugins.withType(AndroidBasePlugin).configureEach {
        android {
            compileSdk 35
            defaultConfig {
                minSdk 9
                targetSdk compileSdk
                vectorDrawables.useSupportLibrary = true
            }
            lint {
                abortOnError true
                checkReleaseBuilds false
            }
            compileOptions {
                sourceCompatibility JavaVersion.VERSION_1_8
                targetCompatibility JavaVersion.VERSION_1_8
            }
        }
    }
}
